### ISSUE TITLE
Support for Sublime Text 3

### ISSUE THREAD

**Issue by hieuh25** [brianriley/sublime-dpaste#4]
Hi I've made a similar package as yours yesterday without knowing your package is available for ST2: https://github.com/H25/dpaste-sublime

Since I'm mainly using ST3, I would love to have my package available on Package Control so other ST3 users can benefit from it. However, as it's stated in my pull request: https://github.com/wbond/package_control_channel/pull/3181. There are no need for 2 similar packages out there, so there are 2 solutions that @FichteFoll suggested:
- I can fork this repo, merge it with my code and create a pull request that you can accept, please note that my code is pretty different to yours.
- If you don't have any plan or time for further updating this repo, please comment on the above pull request so that @FichteFoll might replace your current package with mine.

Looking forward to seeing your comment soon.

**Comment by brianriley** [comment]
I commented on the pull request. It's fine to remove my package from the channel.
